### ISSUE TITLE
typescript support？

### ISSUE THREAD

**Issue by masx200** [microlinkhq/browserless#418] opened 2022-09-06 09:24 UTC
### Prerequisites

- [x] I'm using the last version.
- [x] My node version is the same as declared as `package.json`.

### Subject of the issue

Describe your issue here.

### Steps to reproduce

> **Note**: You can reproduce the code using [interactive Node.js shell by Runkit](https://npm.runkit.com/browserless).

Tell us how to reproduce this issue.

### Expected behaviour

Tell us what should happen

### Actual behaviour

Tell us what happens instead
typescript support？

**Comment by Kikobeats** [comment] 2022-09-06 09:28
duplicate of https://github.com/microlinkhq/browserless/issues/334#issuecomment-980793757

**Closed by Kikobeats** 2022-09-06 09:28 UTC
Labels: question
